---
- name: "Configure Server (Universal: x86/ARM + Swap)"
  hosts: all
  become: true

  vars_files:
    - secrets.yml

  vars:
    target_user: "{{ ansible_user_id }}"
    master_key_path: "ansible_master.pub"
    install_docker: true
    install_tailscale: true
    swap_size_gb: 2
    arch_mapping:
      x86_64: amd64
      aarch64: arm64

  tasks:
    # ----------------------------------------------------------------
    # 1. USER BASELINE
    # ----------------------------------------------------------------
    - name: Ensure user 'ubuntu' exists
      user:
        name: ubuntu
        shell: /bin/bash
        groups: sudo,docker
        append: yes
        state: present

    - name: Authorize master key for 'ubuntu'
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', master_key_path) }}"

    - name: Create sudoers file for ubuntu
      copy:
        content: 'ubuntu ALL=(ALL) NOPASSWD:ALL'
        dest: /etc/sudoers.d/ubuntu
        mode: '0440'
        validate: 'visudo -cf %s'

    # ----------------------------------------------------------------
    # 2. PREP & CHECKS
    # ----------------------------------------------------------------
    - name: Check if Docker is already installed
      command: docker --version
      register: docker_check
      changed_when: false
      failed_when: false

    - name: Update apt cache and upgrade
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600

    - name: Install core dependencies
      apt:
        name: [ca-certificates, curl, gnupg, lsb-release, git, htop, ufw, jq]
        state: present

    # ----------------------------------------------------------------
    # 3. SWAP SETUP
    # ----------------------------------------------------------------
    - name: Check if swap file exists
      stat:
        path: /swapfile
      register: swap_file_check

    - name: Create swap file
      command: "fallocate -l {{ swap_size_gb }}G /swapfile"
      when: not swap_file_check.stat.exists

    - name: Set secure permissions on swap file
      file:
        path: /swapfile
        owner: root
        group: root
        mode: '0600'

    - name: Format swap file
      command: mkswap /swapfile
      when: not swap_file_check.stat.exists

    - name: Enable swap and persist in fstab
      mount:
        name: none
        src: /swapfile
        fstype: swap
        opts: sw
        passno: 0
        dump: 0
        state: present

    # ----------------------------------------------------------------
    # 4. DOCKER SETUP (Conditional)
    # ----------------------------------------------------------------
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when:
        - install_docker | bool
        - docker_check.rc != 0

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch={{ arch_mapping[ansible_architecture] | default('amd64') }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
      when:
        - install_docker | bool
        - docker_check.rc != 0

    - name: Install Docker Engine
      apt:
        name: [docker-ce, docker-ce-cli, containerd.io, docker-compose-plugin]
        state: present
        update_cache: yes
      when:
        - install_docker | bool
        - docker_check.rc != 0

    - name: Add target user to Docker group
      user:
        name: "{{ target_user }}"
        groups: docker
        append: yes
      when: install_docker | bool

    # ----------------------------------------------------------------
    # 5. TAILSCALE SETUP
    # ----------------------------------------------------------------
    - name: Add Tailscale GPG key
      apt_key:
        url: https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.noarmor.gpg
        state: present
      when: install_tailscale | bool

    - name: Add Tailscale repository
      apt_repository:
        repo: "deb https://pkgs.tailscale.com/stable/ubuntu/ {{ ansible_distribution_release }} main"
        state: present
      when: install_tailscale | bool

    - name: Install Tailscale
      apt:
        name: tailscale
        state: present
      when: install_tailscale | bool

    - name: Check Tailscale status
      command: tailscale status
      register: tailscale_status
      changed_when: false
      failed_when: false
      when: install_tailscale | bool

    - name: Connect Tailscale
      command: tailscale up --authkey={{ tailscale_auth_key }} --ssh
      when:
        - install_tailscale | bool
        - tailscale_status.rc != 0
      no_log: true

    # ----------------------------------------------------------------
    # 6. FIREWALL
    # ----------------------------------------------------------------
    - name: Allow SSH
      ufw:
        rule: allow
        name: OpenSSH

    - name: Enable UFW
      ufw:
        state: enabled

