---
- name: Standardize Users to 'ubuntu'
  hosts: all
  become: true
  vars:
    # Make sure this matches the location of your NEW master public key
    master_key_path: "ansible_master.pub"

  tasks:
    # 1. Create the 'ubuntu' user (if it doesn't exist, like on GCP)
    - name: Ensure user 'ubuntu' exists
      user:
        name: ubuntu
        shell: /bin/bash
        # We add them to sudo (admin) and docker groups immediately
        groups: sudo,docker
        append: yes
        state: present

    # 2. Set up SSH Access for 'ubuntu' using Master Key
    - name: Authorize Master Key for 'ubuntu'
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', master_key_path) }}"

    # 3. Ensure 'ubuntu' can sudo without a password (The Clean Way)
    # Instead of editing existing files, we create a dedicated config file.
    - name: Create sudoers file for ubuntu
      copy:
        content: 'ubuntu ALL=(ALL) NOPASSWD:ALL'
        dest: /etc/sudoers.d/ubuntu
        mode: '0440'
        validate: 'visudo -cf %s'
